# Generated by Django 4.2.3 on 2023-08-10 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_display_text',
        ),
    ]
