# Generated by Django 4.2.3 on 2023-08-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='participants_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
